"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""


class Project:
    """
    :type p_id: int | None
    :type p_name: str | None
    """

    def __init__(self):
        self.p_id = None  # t
        self.p_name = None  # t
