"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""


class ProjectLi:
    """
    :type p_id: object | None
    :type p_name: object | None
    :type p_tasks_count: object | None
    """

    def __init__(self):
        self.p_id = None  # q
        self.p_name = None  # q
        self.p_tasks_count = None  # q
