"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""


class Task:
    """
    :type t_id: int | None
    :type p_id: int | None
    :type t_priority: int | None
    :type t_date: str | None
    :type t_subject: str | None
    :type t_comments: str | None
    """

    def __init__(self):
        self.t_id = None  # t
        self.p_id = None  # t
        self.t_priority = None  # t
        self.t_date = None  # t
        self.t_subject = None  # t
        self.t_comments = None  # t
