"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""


class TaskLi:
    """
    :type t_id: object | None
    :type t_date: object | None
    :type t_subject: object | None
    :type t_priority: object | None
    """

    def __init__(self):
        self.t_id = None  # q
        self.t_date = None  # q
        self.t_subject = None  # q
        self.t_priority = None  # q
